analytics.account={"id"\:1124948,"name"\:"G-ABLE QA","uuid"\:"1b63335c-6d06-4055-a318-e2a9f10ade0e","domain"\:"g-able"}
analytics.integration.enable=true
analytics.onpremise.enable=true
analytics.onpremise.organization=null
analytics.onpremise.server=https\://testops.katalon.io
analytics.project={"id"\:3568766,"name"\:"AJINOMOTO","teamId"\:3583903,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:1268548,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3583903,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testreport.autoupload.manualstop.enable=false
onpremise.email=nophasin.s@g-able.com
onpremise.password=S24fmyfgTvfBIUNvNzYQJ6cICu13HFOc
